spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/companydb
    url: jdbc:mysql://localhost:3307/dincergr
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081

app:
  message: "Hello company service!"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

