spring:
  application:
    name: notification
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8084


rabbitmq:
  exchange:
    name: job.exchange
  queue:
    name: job.queue
  routing:
    key: job.tracking
