spring:
  application:
    name: company-service

  datasource:
    url: jdbc:postgresql://localhost:5432/companydb
    username: dincergrn
    password: dincer123
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
