spring:
  application:
    name: company-service

  datasource:
    #url: jdbc:postgresql://localhost:5432/companydb
    url: jdbc:mysql://localhost:3307/dincergr
    username: dincergr
    password: dincergr
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
